# This is a multi-stage Dockerfile and requires >= Docker 17.05
# https://docs.docker.com/engine/userguide/eng-image/multistage-build/
FROM gobuffalo/buffalo:v0.14.6 as builder

RUN mkdir -p $GOPATH/src/handcarry
WORKDIR $GOPATH/src/handcarry

ADD . .
ENV GO111MODULES=on
RUN go get ./...

CMD ["buffalo", "dev"]