FROM gobuffalo/buffalo:v0.18.8

RUN apt-get update && apt-get install -y \
    nano \
    curl \
    netcat \
    && apt-get clean

# Install the desired version of NodeJS
RUN npm cache clean -f && \
    npm install -g n && \
    n 16

RUN curl -o /usr/local/bin/whenavail https://bitbucket.org/silintl/docker-whenavail/raw/1.0.2/whenavail \
     && chmod a+x /usr/local/bin/whenavail

RUN mkdir -p /wecarry
WORKDIR /wecarry

RUN echo 'alias ll="ls -al"' >> ~/.bashrc

COPY go.* ./
ENV GO111MODULE=on

RUN go get github.com/gobuffalo/suite
RUN go get github.com/gobuffalo/httptest
RUN go get github.com/markbates/grift
RUN CGO_ENABLED=0 go get -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv

ADD . .
RUN go get ./...

EXPOSE 6060
CMD ["buffalo", "dev"]
