package actions

import (
	"handcarry/models"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (UserAccessToken)
// DB Table: Plural (user_access_tokens)
// Resource: Plural (UserAccessTokens)
// Path: Plural (/user_access_tokens)
// View Template Folder: Plural (/templates/user_access_tokens/)

// UserAccessTokensResource is the resource for the UserAccessToken model
type UserAccessTokensResource struct {
	buffalo.Resource
}

// List gets all UserAccessTokens. This function is mapped to the path
// GET /user_access_tokens
func (v UserAccessTokensResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	userAccessTokens := &models.UserAccessTokens{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all UserAccessTokens from the DB
	if err := q.All(userAccessTokens); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, userAccessTokens))
}

// Show gets the data for one UserAccessToken. This function is mapped to
// the path GET /user_access_tokens/{user_access_token_id}
func (v UserAccessTokensResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty UserAccessToken
	userAccessToken := &models.UserAccessToken{}

	// To find the UserAccessToken the parameter user_access_token_id is used.
	if err := tx.Find(userAccessToken, c.Param("user_access_token_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, userAccessToken))
}

// Create adds a UserAccessToken to the DB. This function is mapped to the
// path POST /user_access_tokens
func (v UserAccessTokensResource) Create(c buffalo.Context) error {
	// Allocate an empty UserAccessToken
	userAccessToken := &models.UserAccessToken{}

	// Bind userAccessToken to the html form elements
	if err := c.Bind(userAccessToken); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(userAccessToken)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, userAccessToken))
	}

	// and redirect to the user_access_tokens index page
	return c.Render(201, r.Auto(c, userAccessToken))
}

// Update changes a UserAccessToken in the DB. This function is mapped to
// the path PUT /user_access_tokens/{user_access_token_id}
func (v UserAccessTokensResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty UserAccessToken
	userAccessToken := &models.UserAccessToken{}

	if err := tx.Find(userAccessToken, c.Param("user_access_token_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind UserAccessToken to the html form elements
	if err := c.Bind(userAccessToken); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(userAccessToken)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, userAccessToken))
	}

	// and redirect to the user_access_tokens index page
	return c.Render(200, r.Auto(c, userAccessToken))
}

// Destroy deletes a UserAccessToken from the DB. This function is mapped
// to the path DELETE /user_access_tokens/{user_access_token_id}
func (v UserAccessTokensResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty UserAccessToken
	userAccessToken := &models.UserAccessToken{}

	// To find the UserAccessToken the parameter user_access_token_id is used.
	if err := tx.Find(userAccessToken, c.Param("user_access_token_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(userAccessToken); err != nil {
		return errors.WithStack(err)
	}

	// Redirect to the user_access_tokens index page
	return c.Render(200, r.Auto(c, userAccessToken))
}
