// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type File struct {
	ID            string     `json:"id"`
	URL           string     `json:"url"`
	URLExpiration *time.Time `json:"urlExpiration"`
}

type NewMessage struct {
	Content  string  `json:"content"`
	PostID   string  `json:"postID"`
	ThreadID *string `json:"threadID"`
}

type NewOrganization struct {
	Name       string  `json:"name"`
	URL        *string `json:"url"`
	AuthType   string  `json:"authType"`
	AuthConfig string  `json:"authConfig"`
}

type NewOrganizationDomain struct {
	Domain         string `json:"domain"`
	OrganizationID string `json:"organizationID"`
}

type NewPostImage struct {
	File   graphql.Upload `json:"file"`
	PostID string         `json:"postID"`
}

type UpdatedOrganization struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	URL        *string `json:"url"`
	AuthType   string  `json:"authType"`
	AuthConfig string  `json:"authConfig"`
}

type PostRole string

const (
	PostRoleCreatedby PostRole = "CREATEDBY"
	PostRoleReceiving PostRole = "RECEIVING"
	PostRoleProviding PostRole = "PROVIDING"
)

var AllPostRole = []PostRole{
	PostRoleCreatedby,
	PostRoleReceiving,
	PostRoleProviding,
}

func (e PostRole) IsValid() bool {
	switch e {
	case PostRoleCreatedby, PostRoleReceiving, PostRoleProviding:
		return true
	}
	return false
}

func (e PostRole) String() string {
	return string(e)
}

func (e *PostRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostRole", str)
	}
	return nil
}

func (e PostRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PostStatus string

const (
	PostStatusOpen      PostStatus = "OPEN"
	PostStatusCommitted PostStatus = "COMMITTED"
	PostStatusAccepted  PostStatus = "ACCEPTED"
	PostStatusReceived  PostStatus = "RECEIVED"
	PostStatusCompleted PostStatus = "COMPLETED"
	PostStatusRemoved   PostStatus = "REMOVED"
)

var AllPostStatus = []PostStatus{
	PostStatusOpen,
	PostStatusCommitted,
	PostStatusAccepted,
	PostStatusReceived,
	PostStatusCompleted,
	PostStatusRemoved,
}

func (e PostStatus) IsValid() bool {
	switch e {
	case PostStatusOpen, PostStatusCommitted, PostStatusAccepted, PostStatusReceived, PostStatusCompleted, PostStatusRemoved:
		return true
	}
	return false
}

func (e PostStatus) String() string {
	return string(e)
}

func (e *PostStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostStatus", str)
	}
	return nil
}

func (e PostStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PostType string

const (
	PostTypeRequest PostType = "REQUEST"
	PostTypeOffer   PostType = "OFFER"
)

var AllPostType = []PostType{
	PostTypeRequest,
	PostTypeOffer,
}

func (e PostType) IsValid() bool {
	switch e {
	case PostTypeRequest, PostTypeOffer:
		return true
	}
	return false
}

func (e PostType) String() string {
	return string(e)
}

func (e *PostType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostType", str)
	}
	return nil
}

func (e PostType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
